// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmr0n51FwWyTS1LVFXN9xk5cEeUybp3kI',
    appId: '1:465112543665:web:e0ad563d9d01135f990d90',
    messagingSenderId: '465112543665',
    projectId: 'semana5-de37f',
    authDomain: 'semana5-de37f.firebaseapp.com',
    databaseURL: 'https://semana5-de37f-default-rtdb.firebaseio.com',
    storageBucket: 'semana5-de37f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR7GqAg86zQ_IJV2FtxCHS8OVRza-Von4',
    appId: '1:465112543665:android:7b69b1b0f6c48ce8990d90',
    messagingSenderId: '465112543665',
    projectId: 'semana5-de37f',
    databaseURL: 'https://semana5-de37f-default-rtdb.firebaseio.com',
    storageBucket: 'semana5-de37f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmr0n51FwWyTS1LVFXN9xk5cEeUybp3kI',
    appId: '1:465112543665:web:1e6d7c9e5c672f9d990d90',
    messagingSenderId: '465112543665',
    projectId: 'semana5-de37f',
    authDomain: 'semana5-de37f.firebaseapp.com',
    databaseURL: 'https://semana5-de37f-default-rtdb.firebaseio.com',
    storageBucket: 'semana5-de37f.firebasestorage.app',
  );
}
